# python-connection-for-presto
I am unable to connect to Presto using the below connections.  below is the related code:  import prestodb from sqlalchemy.engine import create_engine engine = create_engine("jdbc:presto://Username:password@Hostname:Port/Catalog").   Can anyone suggest the right connection that i can use to connect to Prestodb
